### ISSUE TITLE
研究一下秒杀技术啊，加群519970716

### ISSUE THREAD

**Issue by nicholas0707** [HelloMaoTai/jd-seckill-maotai#4]
平时不在JD买东西，只能搞天猫了，加群研究一下技术啊

**Comment by unclehuahua** [comment]
这是来自 Jo.Vick的自动回复邮件。
 
您好，您的邮件我已收到，我会尽快查阅。祝你身体健康，生活愉快，工作顺利。

**Comment by unclehuahua** [comment]
这是来自 Jo.Vick的自动回复邮件。
 
您好，您的邮件我已收到，我会尽快查阅。祝你身体健康，生活愉快，工作顺利。

**Comment by 66zai** [comment]
This is an automatic reply, confirming that your e-mail was received.Thank you----------------------------------------------------------您的E-mail我已经收到，如果看到定会很快给您答复。
